version: "3.8"
services:
  php-fpm:
    image: nexus.newton-technology.ru:8445/laboratory/elfimov/php-fpm
    volumes:
      - ./application:/var/www/html
  nginx:
    image: nginx
    ports:
      - "8100:80"
    depends_on:
      - php-fpm
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: newton
      POSTGRES_USER: chat
    ports:
      - "9100:5432"
