version: "3.8"
services:

  nginx:
    image: nexus.newton-technology.ru:8445/laboratory/elfimov/nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./entrypoint-fcgiwrap.sh:/docker-entrypoint.d/entrypoint-fcgiwrap.sh
      - ./test.sh:/usr/lib/cgi/test.sh
